services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
