export const grusGrabb = [
    // 'Leo36737',
    'Reeduns',
    'TheLewenhaupt',
    'smashdude1',
    'DoomGladiator',
    'ChimpNE',
    // 'darkeningday',
    'TEEEMO',
    // 'Loot',
    // 'Forssa',
    // 'Spex8',
    // 'Exmortius',
    // 'xXitsyaboiXx',
    // 'Pappenos',
]

export const summonerSpells = {
    1: 'SummonerBoost',
    3: 'SummonerExhaust',
    4: 'SummonerFlash',
    6: 'SummonerHaste',
    7: 'SummonerHeal',
    11: 'SummonerSmite',
    12: 'SummonerTeleport',
    13: 'SummonerMana',
    14: 'SummonerDot',
    21: 'SummonerBarrier',
    30: 'SummonerPoroRecall',
    31: 'SummonerPoroThrow',
    32: 'SummonerSnowball',
    39: 'SummonerSnowURFSnowball_Mark',
    54: 'Summoner_UltBookPlaceholder',
    55: 'Summoner_UltBookSmitePlaceholder',
}

export const leagueRanks = {
    GRANDMASTER: 1,
    MASTER: 2,
    DIAMOND: 3,
    PLATINUM: 4,
    GOLD: 5,
    SILVER: 6,
    BRONZE: 7,
    IRON: 8,
    UNRANKED: 9,
}
