import Head from 'next/head'
import React from 'react'
import Header from '../components/Header'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Grabbarna grus stats</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Component {...pageProps} />
        </>
    )
}

export default MyApp
