import Head from 'next/head'
import React from 'react'
import Header from '../components/Header'
import '../styles/globals.css'
import { RecoilRoot } from 'recoil'

function MyApp({ Component, pageProps }) {
    return (
        <RecoilRoot>
            <Head>
                <title>Grabbarna Grus</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <Header /> */}
            <Component {...pageProps} />
        </RecoilRoot>
    )
}

export default MyApp
